### PR TITLE
Add support for app level configuration

### LINKED ISSUE #2: Support Configurable Loading of CSS
Hello - I'd like to bring my own css. It would be nice if this addon support some app-level configurations.

### PR DESCRIPTION
**Pull request by donaldwasserman**
Fixes #2

### CODE REVIEW

**Comment by tigressbailey** [comment]
@donaldwasserman Build failed. Can you please look into it?

**Comment by donaldwasserman** [comment]
@tigressbailey Sorry, copy paste issue.

**Comment by tigressbailey** [comment]
💯

**Comment by tigressbailey** [comment]
@donaldwasserman The new feature is launched in v1.2.1.

And I add you into the contributor list in README.md

Thanks again for the great idea.

**Pull request merged**
